### ISSUE TITLE
[FEATURE] Font properties

### ISSUE THREAD

**Issue by willster277** [willster277/connect-css#3]
**Is your feature request related to a problem? Please describe.**
ConnectCSS does not currently provide font customization

**Describe the solution you'd like**
ConnectCSS should implement fonts in some such form;
```css
[helvetica] { font-family: 'Helvetica', 'Arial', sans-serif; }
```
```html
<p helvetica>This text will display in the Helvetica font</p>
```
